baseURL = 'https://waibu.bajo.app'
languageCode = 'en-us'
title = 'Bajo Framework'
publishDir = './docs'

[module]
    # uncomment line below for temporary local development of module,
    # when using a 'theme' as a git submodule or git cloned files
    replacements = "github.com/ardhi/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/ardhi/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
[params]
    [params.social]
        github = "ardhi"
    [params.docs]
        title = "Documentations"
    [params.footer]
        version = true
        copyright = "Copyright &copy; 2025 by [Ardhi Lukianto](https://github.com/ardhi). All rights reserved."
[menu]
    [[menu.primary]]
        name = "Documentations"
        url = "docs/"
        identifier = "docs"
        weight = 10
    [[menu.primary]]
        name = "Discussions"
        url = "https://github.com/ardhi/waibu/discussions"
        identifier = "discussions"
        weight = 20
    [[menu.primary]]
        name = "Bajo"
        url = "https://bajo.app"
        identifier = "bajo"
        weight = 30